### ISSUE TITLE
API is throwing 500 errors

### ISSUE THREAD

**Issue by grahamjamesr7** [wcrasta/idb#84]
Hey guys, we're the team that's querying your API. Our code has been querying it successfully up until about 30 minutes ago, and it's throwing 500's now. Just thought we'd let you know that there's an issue. (You may already know about it.)

**Comment by grahamjamesr7** [comment]
Just kidding, small error on our part, that was my bad!

**Comment by wcrasta** [comment]
Hey guys,

Wanted to let y'all know that I don't think you're supposed to be using our API.

**Comment by grahamjamesr7** [comment]
Yeah looks like there was an error on the part of our data visualization team. You're right. Thanks for the heads up lol
